import { Category, City, Business, SubscriptionPlan, SubscriptionPayment, CardTemplate } from './types';

export const CITIES_DATA: City[] = [
  { id: 'tehran', name: 'تهران', province: 'تهران', popular: true },
  { id: 'esfahan', name: 'اصفهان', province: 'اصفهان', popular: true },
  { id: 'mashhad', name: 'مشهد', province: 'خراسان رضوی', popular: true },
  { id: 'shiraz', name: 'شیراز', province: 'فارس', popular: true },
  { id: 'tabriz', name: 'تبریز', province: 'آذربایجان شرقی', popular: true },
  { id: 'karaj', name: 'کرج', province: 'البرز', popular: true },
  { id: 'ahvaz', name: 'اهواز', province: 'خوزستان', popular: false },
  { id: 'rasht', name: 'رشت', province: 'گیلان', popular: false },
  { id: 'qom', name: 'قم', province: 'قم', popular: false },
  { id: 'kerman', name: 'کرمان', province: 'کرمان', popular: false },
  { id: 'hamedan', name: 'همدان', province: 'همدان', popular: false },
  { id: 'yazd', name: 'یزد', province: 'یزد', popular: false },
];

export const CATEGORIES_DATA: Category[] = [
  { id: 'auto', title: 'خدمات خودرو و مکانیکی', icon: 'Car', count: 142, slug: 'auto-services' },
  { id: 'beauty', title: 'زیبایی، پوست و سلامت', icon: 'Sparkles', count: 198, slug: 'beauty-wellness' },
  { id: 'building', title: 'دکوراسیون و تاسیسات ساختمان', icon: 'Hammer', count: 115, slug: 'building-decor' },
  { id: 'restaurant', title: 'کافه، رستوران و کترینگ', icon: 'UtensilsCrossed', count: 230, slug: 'food-cafe' },
  { id: 'tech', title: 'فناوری، موبایل و کامپیوتر', icon: 'Laptop', count: 88, slug: 'tech-repair' },
  { id: 'medical', title: 'کلینیک و دندان‌پزشکی', icon: 'Stethoscope', count: 164, slug: 'medical-care' },
  { id: 'legal', title: 'وکالت، حسابداری و بیمه', icon: 'Scale', count: 76, slug: 'legal-finance' },
  { id: 'education', title: 'آموزشگاه، زبان و مهارت', icon: 'GraduationCap', count: 94, slug: 'education' },
];

export const CARD_TEMPLATES_DATA: CardTemplate[] = [
  {
    id: 'tmpl-modern-minimal',
    name: 'مینیمال سپید مدرن',
    designerName: 'مهرداد رضایی',
    designerCode: 'DES-104',
    designerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    themeStyle: 'minimal',
    bgGradient: 'from-slate-900 via-slate-800 to-indigo-950',
    accentColor: '#3b82f6',
    textColor: '#ffffff',
    previewImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    usesCount: 342,
    rating: 4.9,
  },
  {
    id: 'tmpl-royal-gold',
    name: 'رویال بلک اند گلد',
    designerName: 'سارا تهرانی',
    designerCode: 'DES-208',
    designerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    themeStyle: 'luxury',
    bgGradient: 'from-neutral-950 via-zinc-900 to-stone-900',
    accentColor: '#eab308',
    textColor: '#fef08a',
    previewImage: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=600&auto=format&fit=crop&q=80',
    usesCount: 512,
    rating: 4.95,
  },
  {
    id: 'tmpl-tech-cyan',
    name: 'الکترون سایبر بلوز',
    designerName: 'کامران امینی',
    designerCode: 'DES-319',
    designerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    themeStyle: 'modern',
    bgGradient: 'from-blue-950 via-cyan-950 to-slate-900',
    accentColor: '#06b6d4',
    textColor: '#e0f2fe',
    previewImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    usesCount: 289,
    rating: 4.8,
  },
];

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz-1',
    title: 'مرکز تخصصی تیونینگ و دیتیلینگ خودرو پارس راد',
    slug: 'pars-rad-detailing',
    managerName: 'مهندس رادمنش',
    category: 'خدمات خودرو و مکانیکی',
    categoryId: 'auto',
    city: 'تهران',
    cityId: 'tehran',
    district: 'پاسداران',
    address: 'تهران، خیابان پاسداران، نبش گلستان چهارم، پلاک ۱۸',
    phone: '02122334455',
    mobile: '09121112233',
    whatsapp: '09121112233',
    instagram: 'parsrad_detailing',
    telegram: 'parsrad_auto',
    eitaa: 'parsrad_official',
    bale: 'parsrad_bale',
    website: 'https://parsrad-carcare.ir',
    rating: 4.9,
    reviewsCount: 38,
    viewsCount: 2450,
    isOpen: true,
    workingHours: 'همه روزه از ساعت ۰۹:۰۰ الی ۲۱:۰۰ (جمعه‌ها با هماهنگی)',
    bannerImage: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=200&auto=format&fit=crop&q=80',
    description: 'مجموعه تخصصی پارس راد با بیش از ۱۵ سال سابقه، برترین مرکز اجرای پوشش نانو سرامیک ۱۰ ساله، احیای تخصصی رنگ، کاورهای ضدخش بدنه و صفرشویی فوق مدرن در شمال تهران می‌باشد. کلیه خدمات دارای کارت گارانتی معتبر و ضمانت ماندگاری است.',
    shortBio: 'اجرای نانوسرامیک، کاورهای رنگی و شفاف، پولیش سه مرحله‌ای با دستگاه‌های آلمانی Rupes',
    establishedYear: 1389,
    hasLicense: true,
    licenseNumber: 'ص/۹۸/۲۲۳۵۱',
    licenseUnionName: 'اتحادیه صنف دارندگان تعمیرگاه و اتوسرویس تهران',
    isUnionMember: true,
    hasWarranty: true,
    warrantyTerms: 'ضمانت کتبی ۳ تا ۱۰ ساله برای پوشش سرامیک و تعویض رایگان بخش‌های آسیب‌دیده',
    hasShowcase: true,
    isFeatured: true,
    isVerifiedByAdmin: true,
    selectedTemplateId: 'tmpl-royal-gold',
    designerReferralCode: 'DES-208',
    coordinates: { lat: 35.7721, lng: 51.4612 },
    distanceKm: 1.8,
    products: [
      {
        id: 'p-1',
        title: 'پکیج سرامیک بدنه ۱۰ ساله الماسی (Gyeon)',
        description: 'شامل پولیش چندمرحله‌ای، آینه‌ای کردن رنگ و اجرای ۵ لایه نانوسرامیک هیدروفوبیک ضدخش',
        price: 24500000,
        priceFormatted: '۲۴,۵۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&auto=format&fit=crop&q=80',
        categoryName: 'خدمات سرامیک',
        isSpecial: true,
      },
      {
        id: 'p-2',
        title: 'کاور محافظتی شفاف بدنه (PPF هگزیس فرانسه)',
        description: 'محافظت کامل در برابر سنگ‌خوردگی، تصادفات جزئی و خط و خش با ویژگی خودترمیمی حرارتی',
        price: 85000000,
        priceFormatted: '۸۵,۰۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=600&auto=format&fit=crop&q=80',
        categoryName: 'کاور بدنه',
        isSpecial: true,
      },
      {
        id: 'p-3',
        title: 'احیا و پولیش ۳ مرحله‌ای لوکس',
        description: 'حذف کامل خطوط هولوگرامی، سوختگی‌های آفتاب و ماتی رنگ با واکس کارنوبا اصل',
        price: 9800000,
        priceFormatted: '۹,۸۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&auto=format&fit=crop&q=80',
        categoryName: 'پولیش و ریکاوری',
      }
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80'
    ],
    reviews: [
      {
        id: 'r-1',
        userName: 'علیرضا شایگان',
        rating: 5,
        comment: 'سرامیک خودروی لکسوس رو اینجا انجام دادم، بعد از یک سال هنوز کیفیت و آبگریزی بدنه مثل روز اوله. برخورد پرسنل عالی و سر وقت تحویل دادن.',
        date: '۱۴ اردیبهشت ۱۴۰۴',
        reply: 'با تشکر از حسن اعتماد شما جناب شایگان عزیز، خوشحالیم که راضی بودید.'
      },
      {
        id: 'r-2',
        userName: 'پرهام میرزایی',
        rating: 5,
        comment: 'کاور شفاف روی پورشه اجرا کردن که هیچ خط برشی مشخص نیست، بسیار حرفه‌ای و تمیز.',
        date: '۲۹ فروردین ۱۴۰۴'
      }
    ]
  },
  {
    id: 'biz-2',
    title: 'کلینیک دندان‌پزشکی دکتر نیلوفر کیانی',
    slug: 'dr-kiani-dental-clinic',
    managerName: 'دکتر نیلوفر کیانی (جراح و دندانپزشک)',
    category: 'کلینیک و دندان‌پزشکی',
    categoryId: 'medical',
    city: 'اصفهان',
    cityId: 'esfahan',
    district: 'چهارباغ بالا',
    address: 'اصفهان، خیابان چهارباغ بالا، مجتمع تجاری پزشکی پارسیان، طبقه ۴',
    phone: '03136284900',
    mobile: '09132223344',
    whatsapp: '09132223344',
    instagram: 'dr.kiani_dentistry',
    telegram: 'drkianidental',
    website: 'https://drkianidental.ir',
    rating: 4.8,
    reviewsCount: 54,
    viewsCount: 3120,
    isOpen: true,
    workingHours: 'شنبه تا چهارشنبه از ۱۶:۰۰ الی ۲۱:۰۰',
    bannerImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=200&auto=format&fit=crop&q=80',
    description: 'کلینیک دندانپزشکی تخصصی دیجیتال دکتر کیانی با بهره‌گیری از تجهیزات اسکن سه‌بعدی و کدکم، کلیه خدمات ایمپلنت‌های فوری، لمینت سرامیکی و طراحی لبخند را با نهایت دقت، بدون درد و با متریال اورجینال سوئیسی و آلمانی ارائه می‌نماید.',
    shortBio: 'طراحی تخصصی خط لبخند، ایمپلنت بدون جراحی با راهنمای دیجیتال، ونیر کامپوزیت و لمینت',
    establishedYear: 1394,
    hasLicense: true,
    licenseNumber: 'ن/پ/۱۴۴۲۹',
    licenseUnionName: 'سازمان نظام پزشکی استان اصفهان',
    isUnionMember: true,
    hasWarranty: true,
    warrantyTerms: 'گارانتی ۱۰ ساله ایمپلنت سوئیسی و ضمانت تعویض بدون قید و شرط',
    hasShowcase: true,
    isFeatured: true,
    isVerifiedByAdmin: true,
    selectedTemplateId: 'tmpl-modern-minimal',
    designerReferralCode: 'DES-104',
    coordinates: { lat: 32.6391, lng: 51.6672 },
    distanceKm: 3.2,
    products: [
      {
        id: 'p-201',
        title: 'ایمپلنت دیجیتال فوری Straumann سوئیس',
        description: 'کاشت دندان در یک جلسه همراه با روکش موقت و طراحی نرم‌افزاری سه‌بعدی',
        price: 28000000,
        priceFormatted: '۲۸,۰۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=600&auto=format&fit=crop&q=80',
        categoryName: 'ایمپلنت',
        isSpecial: true,
      },
      {
        id: 'p-202',
        title: 'لمینت سرامیکی Emax آلمان (هر واحد)',
        description: 'طراحی نچرال و شفاف لبخند با مقاومت فوق‌العاده در برابر تغییر رنگ',
        price: 8900000,
        priceFormatted: '۸,۹۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600&auto=format&fit=crop&q=80',
        categoryName: 'زیبایی',
        isSpecial: true,
      }
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=800&auto=format&fit=crop&q=80'
    ],
    reviews: [
      {
        id: 'r-201',
        userName: 'فرشته احمدی',
        rating: 5,
        comment: 'محیط بسیار تمیز، استریل و بدون معطلی. لمینت‌های من خیلی طبیعی و زیبا شد.',
        date: '۱۰ اردیبهشت ۱۴۰۴'
      }
    ]
  },
  {
    id: 'biz-3',
    title: 'کافه و رستوران روف‌گاردن بام شیراز',
    slug: 'baam-shiraz-rooftop-cafe',
    managerName: 'ساسان فرهمند',
    category: 'کافه، رستوران و کترینگ',
    categoryId: 'restaurant',
    city: 'شیراز',
    cityId: 'shiraz',
    district: 'قصرالدشت',
    address: 'شیراز، خیابان قصرالدشت، روبروی باغ هنر، طبقه هفتم برج سپهر',
    phone: '07136302010',
    mobile: '09173334455',
    whatsapp: '09173334455',
    instagram: 'baam_shiraz_cafe',
    telegram: 'baamshiraz',
    eitaa: 'baam_shiraz',
    rating: 4.7,
    reviewsCount: 89,
    viewsCount: 4800,
    isOpen: true,
    workingHours: 'همه‌روزه از ۸:۳۰ صبح تا ۱۲:۳۰ بامداد (سرو صبحانه، ناهار و شام)',
    bannerImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=200&auto=format&fit=crop&q=80',
    description: 'بام شیراز با چشم‌انداز ۳۶۰ درجه و بی‌نظیر از باغات قصرالدشت و کوه‌های شیراز، محیطی رویایی برای دورهمی‌های خانوادگی، قرارهای کاری و تولدها با منوی متنوع غذاهای فرنگی، اصیل شیرازی و بارگرم تخصصی قهوه است.',
    shortBio: 'چشم‌انداز پانوراما، منوی ترکیبی فرنگی و سنتی، اجرای موسیقی زنده در آخر هفته‌ها',
    establishedYear: 1397,
    hasLicense: true,
    licenseNumber: 'ف/۷۶۵۴/ش',
    licenseUnionName: 'اتحادیه صنف رستوران‌داران و تالارهای پذیرایی شیراز',
    isUnionMember: true,
    hasWarranty: false,
    hasShowcase: true,
    isFeatured: true,
    isVerifiedByAdmin: true,
    selectedTemplateId: 'tmpl-royal-gold',
    designerReferralCode: 'DES-208',
    coordinates: { lat: 29.6412, lng: 52.4921 },
    distanceKm: 2.1,
    products: [
      {
        id: 'p-301',
        title: 'استیک ریب‌آی ویژه با سس فلفل سیاه فرانسوی',
        description: '۳۵۰ گرم گوشت راسته گوساله مرینیت شده همراه با پوره سیب‌زمینی ترافل و سبزیجات گریل',
        price: 680000,
        priceFormatted: '۶۸۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
        categoryName: 'غذای اصلی',
        isSpecial: true,
      },
      {
        id: 'p-302',
        title: 'پاستا آلفردو پنه با فیله مرغ تنوری',
        description: 'پنه با سس قارچ و خامه اصیل ایتالیایی و پنیر پارمزان ۲۴ ماهه',
        price: 340000,
        priceFormatted: '۳۴۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=600&auto=format&fit=crop&q=80',
        categoryName: 'پاستا',
      }
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80'
    ],
    reviews: [
      {
        id: 'r-301',
        userName: 'مریم سهرابی',
        rating: 5,
        comment: 'ویوی شب فوق‌العاده است! استیک و پاستا هر دو درجه یک بودند.',
        date: '۵ اردیبهشت ۱۴۰۴'
      }
    ]
  },
  {
    id: 'biz-4',
    title: 'استودیو معماری و دکوراسیون داخلی افق دیزاین',
    slug: 'ofogh-interior-design-studio',
    managerName: 'مهندس آرش بزرگ‌نیا',
    category: 'دکوراسیون و تاسیسات ساختمان',
    categoryId: 'building',
    city: 'تهران',
    cityId: 'tehran',
    district: 'سعادت‌آباد',
    address: 'تهران، سعادت‌آباد، میدان کاج، خیابان سرو غربی، مجتمع سروستان',
    phone: '02122098877',
    mobile: '09124445566',
    whatsapp: '09124445566',
    instagram: 'ofogh_interiordesign',
    telegram: 'ofogh_arch',
    website: 'https://ofoghdesign.com',
    rating: 4.9,
    reviewsCount: 27,
    viewsCount: 1940,
    isOpen: true,
    workingHours: 'شنبه تا پنج‌شنبه از ساعت ۰۹:۳۰ الی ۱۸:۳۰',
    bannerImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&auto=format&fit=crop&q=80',
    description: 'طراحی، بازسازی و اجرای پروژه‌های لوکس مسکونی، تجاری و اداری با رویکرد مینیمال و نئوکلاسیک. ارائه رندرینگ‌های سه‌بعدی پیش از اجرا و تحویل پروژه با مدیریت پیمان شفاف.',
    shortBio: 'طراحی و اجرای صفر تا صد دکوراسیون، کابینت‌های مدرن انزو و پولیشی، هوشمندسازی ساختمان',
    establishedYear: 1391,
    hasLicense: true,
    licenseNumber: 'م/۸۸/۴۱۲۳',
    licenseUnionName: 'سازمان نظام مهندسی ساختمان استان تهران',
    isUnionMember: true,
    hasWarranty: true,
    warrantyTerms: 'ضمانت کتبی ۲ ساله کلیه متریال چوبی و یراق‌آلات Blum اتریش',
    hasShowcase: true,
    isFeatured: false,
    isVerifiedByAdmin: true,
    selectedTemplateId: 'tmpl-tech-cyan',
    designerReferralCode: 'DES-319',
    coordinates: { lat: 35.7891, lng: 51.3721 },
    distanceKm: 4.5,
    products: [
      {
        id: 'p-401',
        title: 'پکیج کامل طراحی سه‌بعدی و نقشه اجرایی فاز ۲',
        description: 'شامل طراحی پلان، نورپردازی، متریال برد، رندرهای ۳۶۰ درجه و آنالیز دقیق متراژ',
        price: 18000000,
        priceFormatted: '۱۸,۰۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80',
        categoryName: 'طراحی معماری',
        isSpecial: true,
      }
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80'
    ],
    reviews: [
      {
        id: 'r-401',
        userName: 'دکتر صابری',
        rating: 5,
        comment: 'بازسازی کلینیک ما رو در موعد مقرر با کیفیتی فراتر از انتظار انجام دادند.',
        date: '۲۲ فروردین ۱۴۰۴'
      }
    ]
  },
  {
    id: 'biz-5',
    title: 'دفتر وکالت و مشاوره حقوقی دادبان عدالت',
    slug: 'dadban-edalat-law-firm',
    managerName: 'دکتر بهرام حیدری (وکیل پایه یک دادگستری)',
    category: 'وکالت، حسابداری و بیمه',
    categoryId: 'legal',
    city: 'مشهد',
    cityId: 'mashhad',
    district: 'احمدآباد',
    address: 'مشهد، بلوار احمدآباد، نبش خیابان پاستور، برج وکلا، واحد ۶۰۲',
    phone: '05138402211',
    mobile: '09155556677',
    whatsapp: '09155556677',
    rating: 4.8,
    reviewsCount: 31,
    viewsCount: 1650,
    isOpen: true,
    workingHours: 'عصرها از ساعت ۱۷:۰۰ الی ۲۰:۳۰ با نوبت قبلی',
    bannerImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=200&auto=format&fit=crop&q=80',
    description: 'مشاوره حقوقی تخصصی در دعاوی ملکی، تجاری، قراردادهای بازرگانی، استارتاپ‌ها و داوری بین‌المللی با بیش از ۲۲ سال تجربه وکالت در دیوان عالی کشور.',
    shortBio: 'وکالت دعاوی ملکی و تجاری، تنظیم قراردادهای پیمانکاری و قراردادهای بین‌المللی',
    establishedYear: 1382,
    hasLicense: true,
    licenseNumber: 'و/۷۶۵۲/خ',
    licenseUnionName: 'کانون وکلای دادگستری استان خراسان',
    isUnionMember: true,
    hasWarranty: false,
    hasShowcase: true,
    isFeatured: false,
    isVerifiedByAdmin: true,
    selectedTemplateId: 'tmpl-modern-minimal',
    designerReferralCode: 'DES-104',
    coordinates: { lat: 36.2972, lng: 59.5841 },
    distanceKm: 5.1,
    products: [
      {
        id: 'p-501',
        title: 'مشاوره تخصصی و تنظیم قرارداد ملکی و تجاری',
        description: 'بررسی اسناد، پیش‌بینی ریسک‌های حقوقی و تدوین بندهای داوری محکم',
        price: 2500000,
        priceFormatted: '۲,۵۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
        categoryName: 'مشاوره حقوقی',
      }
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80'
    ],
    reviews: [
      {
        id: 'r-501',
        userName: 'مهندس کاظمی',
        rating: 5,
        comment: 'تسلط بی‌نظیر به قوانین قراردادها و حل اختلاف ملکی که ماه‌ها درگیرش بودیم.',
        date: '۱۵ اسفند ۱۴۰۳'
      }
    ]
  },
  {
    id: 'biz-6',
    title: 'مرکز تخصصی تعمیرات و گارانتی آیفون و مک‌بوک اپل‌استور تبریز',
    slug: 'apple-store-tabriz-repair',
    managerName: 'مهرداد پاکزاد',
    category: 'فناوری، موبایل و کامپیوتر',
    categoryId: 'tech',
    city: 'تبریز',
    cityId: 'tabriz',
    district: 'ولیعصر',
    address: 'تبریز، کوی ولیعصر، خیابان همافر، برج نگین، پلاک ۴۲',
    phone: '04133319080',
    mobile: '09141118899',
    whatsapp: '09141118899',
    instagram: 'applestore_tabriz',
    rating: 4.9,
    reviewsCount: 46,
    viewsCount: 2280,
    isOpen: true,
    workingHours: 'صبح‌ها ۱۰ الی ۱۴ — عصرها ۱۶:۳۰ الی ۲۱:۳۰',
    bannerImage: 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=1200&auto=format&fit=crop&q=80',
    logoImage: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=200&auto=format&fit=crop&q=80',
    description: 'تعمیرات تخصصی سخت‌افزار و مادربرد آیفون، آیپد و مک‌بوک، تعویض ال‌سی‌دی اورجینال روکاری و باتری با ضمانت سلامت و مهلت تست کتبی.',
    shortBio: 'تعویض گلس و فلت با لیزر، ارتقای حافظه آیفون و تعمیر مادربردهای سوخته',
    establishedYear: 1395,
    hasLicense: true,
    licenseNumber: 'ف/۸۷۱/ت',
    licenseUnionName: 'اتحادیه صنف فناوران رایانه و تجهیزات مخابراتی تبریز',
    isUnionMember: true,
    hasWarranty: true,
    warrantyTerms: '۶ ماه گارانتی بی‌قید و شرط تعویض قطعات سخت‌افزاری اورجینال',
    hasShowcase: true,
    isFeatured: false,
    isVerifiedByAdmin: true,
    selectedTemplateId: 'tmpl-tech-cyan',
    designerReferralCode: 'DES-319',
    coordinates: { lat: 38.0821, lng: 46.3312 },
    distanceKm: 6.8,
    products: [
      {
        id: 'p-601',
        title: 'تعویض باتری اورجینال آیفون با سلامت ۱۰۰٪',
        description: 'بدنه سلول باتری اصلی بدون نمایش پیام Warning در تنظیمات iOS',
        price: 2400000,
        priceFormatted: '۲,۴۰۰,۰۰۰ تومان',
        image: 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=600&auto=format&fit=crop&q=80',
        categoryName: 'تعمیرات آیفون',
      }
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=800&auto=format&fit=crop&q=80'
    ],
    reviews: [
      {
        id: 'r-601',
        userName: 'سینا پاشایی',
        rating: 5,
        comment: 'مک‌بوک من آب خورده بود و هیچ جا قبول نمیکرد، اینجا ظرف ۲ روز مثل روز اول تحویل دادن.',
        date: '۲۸ فروردین ۱۴۰۴'
      }
    ]
  }
];

export const SUBSCRIPTION_PLANS_DATA: SubscriptionPlan[] = [
  {
    id: 'plan-basic',
    title: 'پایه (آزمایشی)',
    durationMonths: 1,
    price: 0,
    badge: 'رایگان',
    features: [
      'ثبت اطلاعات پایه و تماس',
      'نمایش در نتایج جستجو',
      'برچسب‌های شفاف اظهارات',
      '۱ محصول در ویترین',
      'پشتیبانی تیکتی'
    ]
  },
  {
    id: 'plan-bronze',
    title: 'برنزی (فصلی ۳ ماهه)',
    durationMonths: 3,
    price: 1800000,
    features: [
      'نمایش اولویت‌دار در نتایج شهر',
      'ویترین پیشرفته با ۱۰ محصول/خدمت',
      'کارت‌ساز دیجیتال پویا با QR Code',
      'گالری عکس تا ۸ تصویر باکیفیت',
      'آمار بازدید و کلیک‌های ماهانه',
      'پشتیبانی اولویت‌دار'
    ]
  },
  {
    id: 'plan-silver',
    title: 'نقره‌ای (نیم‌ساله ۶ ماهه)',
    durationMonths: 6,
    price: 3200000,
    isPopular: true,
    badge: 'پیشنهاد ویژه اینکارت',
    features: [
      'نمایش در بخش کسب‌وکارهای برگزیده صفحه اصلی',
      'ویترین نامحدود محصولات با دسته‌بندی قیمت',
      'کارت‌ساز اختصاصی با ۳ قالب لوکس + خروجی چاپ',
      'لینک‌دهی مستقیم به شبکه‌های اجتماعی و مسیریاب‌ها',
      'امکان بارگذاری تیزر و ویدیوی محیط کار',
      'نشان ویترین تایید شده اینکارت',
      'گزارش‌گیری دقیق رفتار مشتریان'
    ]
  },
  {
    id: 'plan-gold-vip',
    title: 'طلایی VIP (سالانه ۱۲ ماهه)',
    durationMonths: 12,
    price: 5400000,
    badge: 'حداکثر بازدهی تجاری',
    features: [
      'رتبه ۱ نتایج جستجو و برچسب طلایی VIP',
      'طراحی اختصاصی کارت توسط طراحان ارشد اینکارت',
      'سئوی محلی و ثبت مستقیم بر روی گوگل مپ و نشان',
      'کمپین پیامکی اختصاصی و معرفی در شبکه‌های اجتماعی اینکارت',
      'مدیریت اختصاصی اکانت و پشتیبانی ۲۴ ساعته',
      'تضمین بازگشت وجه در صورت عدم رضایت در ماه اول'
    ]
  }
];

export const INITIAL_PAYMENTS: SubscriptionPayment[] = [
  {
    id: 'pay-1001',
    businessId: 'biz-1',
    businessTitle: 'مرکز تخصصی تیونینگ و دیتیلینگ خودرو پارس راد',
    planId: 'plan-gold-vip',
    planTitle: 'طلایی VIP (سالانه ۱۲ ماهه)',
    amount: 5400000,
    trackingCode: 'TRK-98231450',
    bankName: 'بانک ملت (شبا)',
    receiptImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    date: '۱۴۰۴/۰۲/۰۱',
    status: 'approved',
    startDate: '۱۴۰۴/۰۲/۰۱',
    endDate: '۱۴۰۵/۰۲/۰۱',
    adminNote: 'فیش واریزی بررسی و تایید شد. نشان VIP فعال گردید.'
  },
  {
    id: 'pay-1002',
    businessId: 'biz-2',
    businessTitle: 'کلینیک دندان‌پزشکی دکتر نیلوفر کیانی',
    planId: 'plan-silver',
    planTitle: 'نقره‌ای (نیم‌ساله ۶ ماهه)',
    amount: 3200000,
    trackingCode: 'TRK-44119028',
    bankName: 'بانک پاسارگاد (کارت به کارت)',
    receiptImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    date: '۱۴۰۴/۰۲/۱۰',
    status: 'approved',
    startDate: '۱۴۰۴/۰۲/۱۰',
    endDate: '۱۴۰۴/۰۸/۱۰',
    adminNote: 'تایید شد.'
  },
  {
    id: 'pay-1003',
    businessId: 'biz-4',
    businessTitle: 'استودیو معماری و دکوراسیون داخلی افق دیزاین',
    planId: 'plan-silver',
    planTitle: 'نقره‌ای (نیم‌ساله ۶ ماهه)',
    amount: 3200000,
    trackingCode: 'TRK-77821903',
    bankName: 'بانک سامان',
    receiptImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    date: '۱۴۰۴/۰۲/۱۵',
    status: 'pending',
    adminNote: 'در حال استعلام بانکی توسط واحد مالی'
  }
];
